### ISSUE TITLE
I got this warning 

### ISSUE THREAD

**Issue by sharma-ji** [petercunha/Emotion#1]
Error in loading the saved optimizer state. As a result, your model is starting with a freshly initialized optimizer.
  warnings.warn('Error in loading the saved optimizer '

**Comment by songjd** [comment]
the same error @sharma-ji

**Comment by petercunha** [comment]
Thanks, I'll look into this.
Does this cause the application to crash? Or is it just a warning?

@sharma-ji @songjd

**Comment by SivaKanishka** [comment]
@petercunha I tried reproducing the repo, I am still getting the error mentioned by @sharma-ji. 
This the error log:

```
UserWarning: Error in loading the saved optimizer state. As a result, your model is starting with a freshly initialized optimizer.
  warnings.warn('Error in loading the saved optimizer '
: cannot connect to X server
```

**Comment by timrockefeller** [comment]
it crashed
just a window flashed
and the progress stopped immediately

**Comment by petercunha** [comment]
@timrockefeller error message?

**Comment by timrockefeller** [comment]
@petercunda well it solved
the camera drivers update required <:P

**Comment by feimax** [comment]
how to update the camera driver? I have the save problem

**Comment by timrockefeller** [comment]
> how to update the camera driver? I have the save problem

check if you can enable your camera in other programs like skype
the camera is default disabled
