### ISSUE TITLE
VIDEOIO ERROR: V4L2: Pixel format of incoming image is unsupported by OpenCV; Unable to stop the stream: Device or resource busy

### ISSUE THREAD

**Issue by SKWH8140** [petercunha/Emotion#3]
I was able to make it work by commenting out "video_capture = cv2.VideoCapture(0)" at line 36 of emotions.py

**Comment by petercunha** [comment]
OpenCV has some compatibility issues with certain webcams. You should be able to fix this by changing the following lines to ON in the CMakeLists.txt and recompiling OpenCV:

```
OCV_OPTION(WITH_V4L            "Include Video 4 Linux support"               ON   IF (UNIX AND NOT ANDROID) )
OCV_OPTION(WITH_LIBV4L         "Use libv4l for Video 4 Linux support"        ON   IF (UNIX AND NOT ANDROID) )
```
