### ISSUE TITLE
are you interested in building a web app on it?

### ISSUE THREAD

**Issue by wiwengweng** [petercunha/Emotion#4]
Hi, glad to see your effort building this system, and I am thinking about building a web app on working pieces like yours. Are you interested in this, and help me out? Thanks.

Andes

**Comment by petercunha** [comment]
Yes, I'd be happy to help out! I can do frontend with either React or Angular, I can also help out on backend if you are ok with using NodeJS.

Please email me the details, I'd like to discuss this idea more!
petercunha8@gmail.com
