### ISSUE TITLE
How to train on my custom data?

### ISSUE THREAD

**Issue by akshatbhargava123** [petercunha/Emotion#5]
Please tell something about how to train the model on my custom data? This project is awesome, I really love it but it's useless unless we don't have ability to train it ourselves.

**Comment by petercunha** [comment]
## To train new models for emotion classification

- Download the fer2013.tar.gz file from [here](https://www.kaggle.com/c/challenges-in-representation-learning-facial-expression-recognition-challenge/data)
- Move the downloaded file to the datasets directory inside this repository.
- Untar the file:
`tar -xzf fer2013.tar`
- Download train_emotion_classifier.py from orriaga's repo [here](https://github.com/oarriaga/face_classification/blob/master/src/train_emotion_classifier.py)
- Run the train_emotion_classification.py file:
`python3 train_emotion_classifier.py`
