### ISSUE TITLE
VIDEOIO Error

### ISSUE THREAD

**Issue by sailsolar** [petercunha/Emotion#6]
Hi,

I am getting the following error when trying to run the project with the mentioned instructions.

```
(vpy3) inspiron:~/Documents/Emotion$ python3 emotions.py 
Using TensorFlow backend.
2018-10-29 20:02:17.572019: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
/home/inspiron/.virtualenvs/vpy3/lib/python3.6/site-packages/keras/engine/saving.py:327: UserWarning: Error in loading the saved optimizer state. As a result, your model is starting with a freshly initialized optimizer.
  warnings.warn('Error in loading the saved optimizer '
VIDEOIO ERROR: V4L2: Pixel format of incoming image is unsupported by OpenCV
Unable to stop the stream: Device or resource busy
VIDEOIO ERROR: V4L: can't open camera by index 0
```
Can you please suggest what may I change or do to make it work?

**Comment by petercunha** [comment]
Looks like you're trying to open a webcam feed that OpenCV doesn't know how to read.

The problem could be:
- You don't have a webcam or video device attached to your computer
- You have a device attached, but you don't have the proper drivers installed
- You have a working webcam, but for some reason it's unsupported by OpenCV


If you can't figure out how to get the webcam feed working, do this instead. On [line 13 of emotions.py](https://github.com/petercunha/Emotion/blob/master/emotions.py#L13), change the boolean to load the sample video:

```python
USE_WEBCAM = False
```

This will load a saved mp4 file and preform emotion analysis on it. Hopefully it will give you a nice demo to play around with.

Let me know if you have any other questions.
Peter
